OBJS:= $(OBJS) ./src/graphics/Display.o ./src/graphics/Graphics.o ./src/graphics/Shader.o \
	./src/graphics/Mesh.o ./src/graphics/Texture.o ./src/graphics/Model.o ./src/graphics/Framebuffer.o \
	./src/graphics/Cubemap.o ./src/graphics/Skybox.o ./src/graphics/Camera.o
